### ISSUE TITLE
how to download ver 0.0.6?

### ISSUE THREAD

**Issue by ToneBe** [willianrod/ODeck#47]
## Summary

someone tell me how to get ver 0.0.6 ?  i am not a coder i do not understand what to do  there is no installer!!???

**Comment by CarolinaMoraes** [comment]
Is this what you're looking for? https://github.com/willianrod/ODeck/releases/tag/v0.0.6
This page contains the links installers for different OSs

**Comment by ToneBe** [comment]
Hi

No this doesn’t help how do I instal v.0.6 there is no exe file for windows like the previous version
Whatever youre asking people to do to obtain it is not clear at all
Please assist me
thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by CarolinaMoraes** [comment]
Hi!

I may be wrong here, and I guess @willianrod can point that out if it is the case, but from what I checked, if you compare the v0.0.5 tag with the v0.0.6 you can see that no changes were made to the app itself, only to the documentation and the build 
process https://github.com/willianrod/ODeck/compare/v0.0.5...v0.0.6
![image](https://github.com/willianrod/ODeck/assets/32900257/12905ae8-238f-42a7-93bc-cff556431a46)
So there is no new installer because there is no newer version of the app yet

**Comment by ToneBe** [comment]
thanks Carol   
any idea when it will be released ?

**Comment by CarolinaMoraes** [comment]
Unfortunately, I don't have that information ://

**Comment by willianrod** [comment]
Yes, @CarolinaMoraes is right, there were no significant code changes from 0.0.5 to 0.0.6 so the build number didn't change.
